server.port=7022

# PostgreSQL datasource
spring.datasource.postgres.jdbc-url=jdbc:postgresql://localhost:5432/alap_reports
spring.datasource.postgres.username=postgres
spring.datasource.postgres.password=root

# MariaDB datasource (AUTO_UNDER_WRITING LIFE)
spring.datasource.mariadb.jdbc-url=jdbc:mariadb://192.168.130.101:3306/autounderwriting_life
spring.datasource.mariadb.username=ausyslive
spring.datasource.mariadb.password=A0100$23

ausys.client.uri.urlBase=http://192.168.130.104/ausys-backend-new
ausys.client.proposal-form.url=/questionnaire/new/get-merged-questionnaire-pdf

storage.proposal.pdf.path=\\\\192.168.130.78\\proposal-pdf
# storage.proposal.pdf.path=C:\\Users\\janith.thiwanka\\Desktop\\Test