server.port=7022

# PostgresSQL database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/techno_test
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# AUTO_UNDER_WRITING LIFE DATABASE PROPERTIES
#spring.datasource.url=jdbc:mariadb://192.168.130.101:3306/autounderwriting_life
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
