server.port=7022

# PostgreSQL datasource
spring.datasource.postgres.jdbc-url=jdbc:postgresql://localhost:5432/alap_reports
spring.datasource.postgres.username=postgres
spring.datasource.postgres.password=root

# MariaDB datasource (AUTO_UNDER_WRITING LIFE)
spring.datasource.mariadb.jdbc-url=jdbc:mariadb://192.168.130.101:3306/autounderwriting_life
spring.datasource.mariadb.username=ausyslive
spring.datasource.mariadb.password=A0100$23
